-- 1. Testimonials Table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  content text not null,
  image_url text,
  rating int default 5 check (rating >= 1 and rating <= 5),
  display_order int default 0,
  is_enabled boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.testimonials enable row level security;

create policy "Allow public read access" on public.testimonials
  for select using (true);

create policy "Allow admin full access" on public.testimonials
  for all using (auth.role() = 'authenticated');

-- 2. SEO Columns for existing tables
alter table public.pages add column if not exists seo_title text;
alter table public.pages add column if not exists seo_description text;

alter table public.projects add column if not exists seo_title text;
alter table public.projects add column if not exists seo_description text;

alter table public.items add column if not exists seo_title text;
alter table public.items add column if not exists seo_description text;

-- 3. Ensure Global SEO Settings exist
insert into public.site_settings (key, value, label, type)
values 
  ('site_description', '"Premium Architecture, Construction, and Interior Design Solutions."', 'Global Site Description (SEO)', 'textarea')
on conflict (key) do nothing;

-- 4. Add Testimonials to Home Layout options if not present
-- We update the JSONB array to include testimonials if it's currently the default
update public.site_settings 
set value = value || '[{"id": "testimonials", "type": "component", "label": "Testimonials", "enabled": true}]'::jsonb
where key = 'home_layout' 
and not (value @> '[{"id": "testimonials"}]'::jsonb);
