-- Run this script to ADD the new features (Items, Layout) without breaking existing tables.

-- 1. Create table public.items if it doesn't exist
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  type text, -- 'Property', 'Apartment', 'Plot', etc.
  price text, -- generic text to handle ranges or currencies if needed
  location text, 
  action_label text default 'Contact Us', -- Button Text
  action_url text, -- Link destination (e.g., tel:..., mailto:..., or /contact)
  is_enabled boolean default true,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.items enable row level security;

-- Policies for items
do $$ 
begin
    if not exists (select 1 from pg_policies where policyname = 'Allow public read access' and tablename = 'items') then
        create policy "Allow public read access" on public.items for select using (true);
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Allow admin full access' and tablename = 'items') then
        create policy "Allow admin full access" on public.items for all using (auth.role() = 'authenticated');
    end if;
end $$;


-- 2. Create table public.item_images if it doesn't exist
create table if not exists public.item_images (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  image_url text not null,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.item_images enable row level security;

-- Policies for item_images
do $$ 
begin
    if not exists (select 1 from pg_policies where policyname = 'Allow public read access' and tablename = 'item_images') then
        create policy "Allow public read access" on public.item_images for select using (true);
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Allow admin full access' and tablename = 'item_images') then
        create policy "Allow admin full access" on public.item_images for all using (auth.role() = 'authenticated');
    end if;
end $$;


-- 3. Initial Seed Data for Home Layout (Only if not already present)
insert into public.site_settings (key, value, label, type)
values (
  'home_layout', 
  '[
    {"id": "hero", "type": "fixed", "label": "Hero Section", "enabled": true},
    {"id": "about", "type": "component", "label": "About Section", "enabled": true},
    {"id": "items", "type": "component", "label": "Featured Items", "enabled": true},
    {"id": "services", "type": "component", "label": "Services", "enabled": true},
    {"id": "portfolio", "type": "component", "label": "Portfolio", "enabled": true},
    {"id": "custom", "type": "component", "label": "Custom Sections", "enabled": true},
    {"id": "contact", "type": "component", "label": "Contact Section", "enabled": true}
   ]'::jsonb,
  'Home Page Layout Order', 
  'json'
) on conflict (key) do nothing;


-- 4. Update custom_sections with mobile support
ALTER TABLE public.custom_sections 
ADD COLUMN IF NOT EXISTS is_mobile_custom boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS mobile_content text,
ADD COLUMN IF NOT EXISTS mobile_css_content text;

-- 5. Create section_images table
create table if not exists public.section_images (
  id bigint generated by default as identity primary key,
  section_id bigint references public.custom_sections(id) on delete cascade not null,
  image_url text not null,
  storage_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.section_images enable row level security;

-- Policies for section_images
do $$ 
begin
    if not exists (select 1 from pg_policies where policyname = 'Allow public read access' and tablename = 'section_images') then
        create policy "Allow public read access" on public.section_images for select using (true);
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Allow admin full access' and tablename = 'section_images') then
        create policy "Allow admin full access" on public.section_images for all using (auth.role() = 'authenticated');
    end if;
end $$;

-- 6. New Hero Settings (Added 2026-03-21)
insert into public.site_settings (key, value, label, type)
values 
  ('hero_title', '"Elevate your business with modern solutions"', 'Hero Title', 'text'),
  ('hero_subtitle', '"Your trusted partner for specialized consulting, technical expertise, and operational excellence."', 'Hero Subtitle', 'textarea'),
  ('hero_highlight_text', '"modern solutions"', 'Hero Highlight Word', 'text'),
  ('hero_highlight_color', '"#f59e0b"', 'Hero Highlight Color', 'text'),
  ('hero_badge_text', '"Excellence in Service"', 'Hero Badge Text', 'text'),
  ('hero_cta_primary', '"Get in Touch"', 'Primary CTA Text', 'text'),
  ('hero_cta_primary_link', '"#contact"', 'Primary CTA Link', 'text'),
  ('hero_cta_secondary', '"View Projects"', 'Secondary CTA Text', 'text'),
  ('hero_cta_secondary_link', '"#portfolio"', 'Secondary CTA Link', 'text'),
  ('hero_text_align', '"center"', 'Hero Text Alignment', 'text'),
  ('hero_height', '"full"', 'Hero Section Height', 'text'),
  ('hero_height_desktop', '"full"', 'Hero Section Height Desktop', 'text'),
  ('hero_bg_type', '"image"', 'Hero Background Type', 'text'),
  ('hero_overlay_opacity', '60', 'Hero Overlay Opacity', 'text'),
  ('hero_bg_image_scroll', '"false"', 'Hero Background scroll', 'text'),
  ('hero_overlay_color_start', '"#000000"', 'Hero Overlay Color Start', 'text'),
  ('hero_overlay_color_end', '"#000000"', 'Hero Overlay Color End', 'text'),
  ('hero_overlay_opacity_start', '60', 'Hero Overlay Opacity Start', 'text'),
  ('hero_overlay_opacity_end', '60', 'Hero Overlay Opacity End', 'text'),
  ('hero_overlay_gradient_angle', '"180"', 'Hero Overlay Gradient Angle', 'text')
on conflict (key) do nothing;

-- 7. Page Images Table (Added for Multi-Image Support on Pages)
create table if not exists public.page_images (
  id bigint generated by default as identity primary key,
  page_id bigint references public.pages(id) on delete cascade not null,
  image_url text not null,
  storage_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.page_images enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where policyname = 'Allow public read access' and tablename = 'page_images') then
        create policy "Allow public read access" on public.page_images for select using (true);
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Allow admin full access' and tablename = 'page_images') then
        create policy "Allow admin full access" on public.page_images for all using (auth.role() = 'authenticated');
    end if;
end $$;
