-- Enable Row Level Security (RLS) is enabled by default on new tables in Supabase, but we explicitly enable it.

-- 1. Site Settings Table
-- Stores all global content (Hero, Contact, About, Socials)
create table public.site_settings (
  key text not null primary key,
  value jsonb not null, -- Using JSONB for flexibility (strings, arrays, objects)
  label text, -- Human readable label for the admin UI
  type text check (type in ('text', 'textarea', 'image', 'json', 'array')) default 'text'
);

alter table public.site_settings enable row level security;

-- Policy: Allow read access to everyone (public content)
create policy "Allow public read access" on public.site_settings
  for select using (true);

-- Policy: Allow all access to authenticated users (Admin)
create policy "Allow admin full access" on public.site_settings
  for all using (auth.role() = 'authenticated');


-- 2. Services Table
create table public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon text, -- FontAwesome class name
  page_url text, -- Link to a dynamic page
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.services enable row level security;

create policy "Allow public read access" on public.services
  for select using (true);

create policy "Allow admin full access" on public.services
  for all using (auth.role() = 'authenticated');


-- 2.1 Pages Table (Dynamic Pages)
create table public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text, -- HTML/Rich text content (legacy fallback)
  layout jsonb default '[]'::jsonb, -- Array of section configurations
  image_url text, -- Hero image URL
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.pages enable row level security;

create policy "Allow public read access" on public.pages
  for select using (true);

-- Policy: Allow admin full access on public.pages
create policy "Allow admin full access" on public.pages
  for all using (auth.role() = 'authenticated');


-- 2.2 Page Images Table
create table public.page_images (
  id bigint generated by default as identity primary key,
  page_id bigint references public.pages(id) on delete cascade not null,
  image_url text not null,
  storage_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.page_images enable row level security;

create policy "Allow public read access" on public.page_images
  for select using (true);

create policy "Allow admin full access" on public.page_images
  for all using (auth.role() = 'authenticated');


-- 3. Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  description text,
  thumbnail_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;

create policy "Allow public read access" on public.projects
  for select using (true);

create policy "Allow admin full access" on public.projects
  for all using (auth.role() = 'authenticated');


-- 4. Project Images Table (Gallery)
create table public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  image_url text not null,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.project_images enable row level security;

create policy "Allow public read access" on public.project_images
  for select using (true);

create policy "Allow admin full access" on public.project_images
  for all using (auth.role() = 'authenticated');


-- 5. Storage Buckets (if not already created via UI)
-- Note: Bucket creation via SQL requires specific privileges, usually done via UI/API.
-- We assume a public bucket named 'images' exists.
-- insert into storage.buckets (id, name, public) values ('images', 'images', true);

-- 6. Custom Sections Table
create table public.custom_sections (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  image_url text,
  is_html boolean default false,
  css_content text,
  is_mobile_custom boolean default false,
  mobile_content text,
  mobile_css_content text,
  display_order int default 0,
  page_id bigint references public.pages(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.custom_sections enable row level security;

create policy "Allow public read access" on public.custom_sections
  for select using (true);

create policy "Allow admin full access" on public.custom_sections
  for all using (auth.role() = 'authenticated');


-- 6.1 Section Images Table (for Custom HTML sections)
create table public.section_images (
  id bigint generated by default as identity primary key,
  section_id bigint references public.custom_sections(id) on delete cascade not null,
  image_url text not null,
  storage_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.section_images enable row level security;

create policy "Allow public read access" on public.section_images
  for select using (true);

create policy "Allow admin full access" on public.section_images
  for all using (auth.role() = 'authenticated');

-- 7. Items Table (Generic Listings, e.g., Products, Services)
create table public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price bigint, -- Stored as whole number (e.g. 10000000)
  location text, 
  action_label text default 'Contact Us', -- Button Text
  action_url text, -- Link destination (e.g., tel:..., mailto:..., or /contact)
  is_enabled boolean default true,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.items enable row level security;

create policy "Allow public read access" on public.items
  for select using (true);

create policy "Allow admin full access" on public.items
  for all using (auth.role() = 'authenticated');

-- 8. Item Images Table
create table public.item_images (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  image_url text not null,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.item_images enable row level security;

create policy "Allow public read access" on public.item_images
  for select using (true);

create policy "Allow admin full access" on public.item_images
  for all using (auth.role() = 'authenticated');


-- 9. Initial Seed Data for Home Layout
-- Insert default layout if not exists
insert into public.site_settings (key, value, label, type)
values (
  'home_layout', 
  '[
    {"id": "hero", "type": "fixed", "label": "Hero Section", "enabled": true},
    {"id": "about", "type": "component", "label": "About Section", "enabled": true},
    {"id": "items", "type": "component", "label": "Featured Items", "enabled": true},
    {"id": "services", "type": "component", "label": "Services", "enabled": true},
    {"id": "portfolio", "type": "component", "label": "Portfolio", "enabled": true},
    {"id": "custom", "type": "component", "label": "Custom Sections", "enabled": true},
    {"id": "contact", "type": "component", "label": "Contact Section", "enabled": true}
   ]'::jsonb,
  'Home Page Layout Order', 
  'json'
) on conflict (key) do nothing;

-- 9.1 Initial Hero Settings
insert into public.site_settings (key, value, label, type)
values 
  ('hero_title', '"Elevate your business with modern solutions"', 'Hero Title', 'text'),
  ('hero_badge_color', '"#f59e0b"', 'Hero Badge Color', 'text'),
  ('hero_subtitle', '"Your trusted partner for specialized consulting, technical expertise, and operational excellence."', 'Hero Subtitle', 'textarea'),
  ('hero_highlight_text', '"modern solutions"', 'Hero Highlight Word', 'text'),
  ('hero_text_color_mode', '"auto"', 'Hero Text Color Mode', 'text'),
  ('hero_text_color', '"#ffffff"', 'Hero Text Color', 'text'),
  ('hero_title_size', '"base"', 'Hero Title Size', 'text'),
  ('hero_highlight_italic', '"false"', 'Hero Highlight Italic', 'text'),
  ('hero_highlight_font', '"inherit"', 'Hero Highlight Font', 'text'),
  ('hero_cutout_image_url', '""', 'Hero Cutout Image URL', 'text'),
  ('hero_cutout_position', '"right"', 'Hero Cutout Position', 'text'),
  ('hero_cutout_size', '"large"', 'Hero Cutout Image Size', 'text'),
  ('hero_highlight_color', '"#f59e0b"', 'Hero Highlight Color', 'text'),
  ('hero_cta_primary', '"Get in Touch"', 'Primary CTA Text', 'text'),
  ('hero_cta_primary_link', '"#contact"', 'Primary CTA Link', 'text'),
  ('hero_cta_primary_color', '"#f59e0b"', 'Primary CTA Color', 'text'),
  ('hero_cta_secondary', '"View Projects"', 'Secondary CTA Text', 'text'),
  ('hero_cta_secondary_link', '"#portfolio"', 'Secondary CTA Link', 'text'),
  ('hero_cta_secondary_color', '"#71717a"', 'Secondary CTA Color', 'text'),
  ('hero_text_align', '"center"', 'Hero Text Alignment', 'text'),
  ('hero_height', '"full"', 'Hero Section Height', 'text'),
  ('hero_height_desktop', '"full"', 'Hero Section Height Desktop', 'text'),
  ('hero_cta_border_radius', '"full"', 'Hero CTA Border Radius', 'text'),
  ('hero_bg_type', '"image"', 'Hero Background Type', 'text'),
  ('hero_bg_video_url', '""', 'Hero Background Video URL', 'text'),
  ('hero_overlay_opacity', '60', 'Hero Overlay Opacity', 'text'),
  ('hero_bg_image_scroll', '"false"', 'Hero Background scroll', 'text'),
  ('hero_overlay_color_start', '"#000000"', 'Hero Overlay Color Start', 'text'),
  ('hero_overlay_color_end', '"#000000"', 'Hero Overlay Color End', 'text'),
  ('hero_overlay_opacity_start', '60', 'Hero Overlay Opacity Start', 'text'),
  ('hero_overlay_opacity_end', '60', 'Hero Overlay Opacity End', 'text'),
  ('hero_overlay_gradient_angle', '"180"', 'Hero Overlay Gradient Angle', 'text'),
  ('hero_overlay_card_show', '"false"', 'Show Hero Overlay Card', 'text'),
  ('hero_overlay_card_icon', '"fa-solid fa-certificate"', 'Hero Overlay Card Icon', 'text'),
  ('hero_overlay_card_title', '"EXPERT ADVISORY"', 'Hero Overlay Card Title', 'text'),
  ('hero_overlay_card_text', '"Senior Consultant specializing in strategic planning and operational transformation."', 'Hero Overlay Card Text', 'textarea'),
  ('hero_overlay_card_position', '"bottom-left"', 'Hero Overlay Card Position', 'text'),
  ('hero_bg_image_url', '"/placeholder.jpg"', 'Hero Background Image URL', 'text'),
  ('about_image_url', '"/placeholder.jpg"', 'About Section Image URL', 'text'),
  ('logo_light_brightness', '"1"', 'Logo Brightness (Light)', 'text'),
  ('logo_light_grayscale', '"0"', 'Logo Grayscale (Light)', 'text'),
  ('logo_light_drop_shadow', '"none"', 'Logo Drop Shadow (Light)', 'text'),
  ('logo_dark_brightness', '"1"', 'Logo Brightness (Dark)', 'text'),
  ('logo_dark_grayscale', '"0"', 'Logo Grayscale (Dark)', 'text'),
  ('logo_dark_drop_shadow', '"none"', 'Logo Drop Shadow (Dark)', 'text'),
  ('nav_show_login', '"true"', 'Show Login Button', 'text'),
  ('nav_show_wishlist', '"true"', 'Show Wishlist Button', 'text'),
  ('nav_show_profile', '"true"', 'Show Profile Button', 'text'),
  ('logo_type', '"image"', 'Logo Display Type', 'text'),
  ('logo_text', '"Brand Name"', 'Logo Text Content', 'text'),
  ('logo_text_font', '"Outfit"', 'Logo Text Font', 'text'),
  ('logo_text_size', '"24"', 'Logo Text Size (px)', 'text'),
  ('logo_text_weight', '"700"', 'Logo Text Weight', 'text'),
  ('logo_text_color_light', '"#000000"', 'Logo Text Color (Light)', 'text'),
  ('logo_text_color_dark', '"#ffffff"', 'Logo Text Color (Dark)', 'text'),
  ('logo_text_shadow_light', '"none"', 'Logo Text Shadow (Light)', 'text'),
  ('logo_text_shadow_dark', '"none"', 'Logo Text Shadow (Dark)', 'text'),
  ('site_primary_color', '"#f59e0b"', 'Site Primary Color', 'text'),
  ('site_secondary_color', '"#71717a"', 'Site Secondary Color', 'text'),
  ('header_menu_config', '{
    "order": ["hero", "about", "items", "services", "portfolio", "contact", "login", "wishlist", "profile"],
    "items": {
      "hero": { "desktop": "show", "mobile": "show" },
      "about": { "desktop": "show", "mobile": "show" },
      "items": { "desktop": "show", "mobile": "show" },
      "services": { "desktop": "show", "mobile": "show" },
      "portfolio": { "desktop": "show", "mobile": "show" },
      "contact": { "desktop": "show", "mobile": "show" },
      "login": { "desktop": "show", "mobile": "show" },
      "wishlist": { "desktop": "show", "mobile": "show" },
      "profile": { "desktop": "show", "mobile": "show" }
    },
    "desktop": {
      "fontSize": "16",
      "fontWeight": "500",
      "alignment": "right",
      "fontFamily": "Outfit"
    },
    "mobile": {
      "fontSize": "14",
      "fontWeight": "500",
      "alignment": "left",
      "fontFamily": "Outfit"
    },
    "moreLabel": "More"
  }'::jsonb, 'Header Menu Configuration', 'json'),
  ('favicon_type', '"image"', 'Favicon Type', 'text'),
  ('favicon_url', '""', 'Favicon Image URL', 'text'),
  ('favicon_icon', '"fa-solid fa-star"', 'Favicon FontAwesome Icon', 'text'),
  ('favicon_icon_color', '"#f59e0b"', 'Favicon Icon Color', 'text')
on conflict (key) do nothing;

-- 10. Profiles Table (Auth)
-- ==========================================
-- USER AUTHENTICATION & BOOKMARKS (Updated)
-- ==========================================

-- 1. Create Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  phone text,
  role text default 'user' check (role in ('admin', 'user')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- 2. Create Bookmarks Table
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  item_id bigint references public.items(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, item_id)
);

-- Enable RLS
alter table public.bookmarks enable row level security;

-- 3. Helper Functions

-- 3a. Profile Creation Trigger Function
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, phone, role)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    'user' -- Defaults to 'user'
  );
  return new;
end;
$$ language plpgsql security definer;

-- 3b. Admin Check Function (Fixes Infinite Recursion)
-- Security Definer bypasses RLS on 'profiles' table to check role safely
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1
    from public.profiles
    where id = auth.uid()
    and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- 4. Triggers

-- Trigger for new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. RLS Policies for Profiles

-- Drop existing policies to prevent conflicts if re-running
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Admins can view all profiles" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

-- Create Policies
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

-- Admin Policy using Secure Function
create policy "Admins can view all profiles" on public.profiles
  for select using (public.is_admin());

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- 6. RLS Policies for Bookmarks

-- Drop existing policies
drop policy if exists "Users can view own bookmarks" on public.bookmarks;
drop policy if exists "Users can create own bookmarks" on public.bookmarks;
drop policy if exists "Users can delete own bookmarks" on public.bookmarks;

-- Create Policies
create policy "Users can view own bookmarks" on public.bookmarks
  for select using (auth.uid() = user_id);

create policy "Users can create own bookmarks" on public.bookmarks
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own bookmarks" on public.bookmarks
  for delete using (auth.uid() = user_id);

-- 7. Column-Level Security for Roles
revoke update on public.profiles from authenticated;
grant update (full_name, phone) on public.profiles to authenticated;

-- 8. Service Role Grants
grant all on public.profiles to service_role;
grant all on public.bookmarks to service_role;

-- 11. Optional Site Content (Widgets)
INSERT INTO public.custom_sections (title, content, is_html, display_order)
VALUES (
  'PluginTek Contact Widget',
  '<section id="plugintek-widget" class="py-12 bg-white dark:bg-black">
    <div class="container mx-auto px-4">
      <iframe
        src="https://your-chatbot-ui.vercel.app/widget/contact-2?tenantId=11111111-1111-1111-1111-111111111111"
        style="width: 100%; height: 700px; border: none; background: transparent;"
        allowtransparency="true"
        title="PluginTek Contact Widget"
      ></iframe>
    </div>
  </section>',
  true,
  99
) ON CONFLICT DO NOTHING;
