-- Supabase SQL Editor script to add Pages and update Services table

-- 1. Create the Pages table
create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text, 
  image_url text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and setup policies
alter table public.pages enable row level security;

drop policy if exists "Allow public read access" on public.pages;
create policy "Allow public read access" on public.pages
  for select using (true);

drop policy if exists "Allow admin full access" on public.pages;
create policy "Allow admin full access" on public.pages
  for all using (auth.role() = 'authenticated');

-- 2. Alter the Services table to add page_url
alter table public.services 
add column if not exists page_url text;
